# Generated by Django 6.0 on 2025-12-09 19:15

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0002_alter_medico_registro_profesional'),
        ('paciente', '0002_alter_paciente_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha_cita', models.DateField(verbose_name='Fecha Cita')),
                ('hora_cita', models.TimeField(verbose_name='Hora Cita')),
                ('duracion_minutos', models.IntegerField(default=30)),
                ('motivo_cita', models.TextField(verbose_name='Motivo Cita')),
                ('estado', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='AGENDADA', max_length=20, verbose_name='Estado Cita')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha_cita'],
            },
        ),
    ]
