# Generated by Django 6.0 on 2025-12-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='registro_profesional',
            field=models.CharField(default='Pendiente', max_length=50, verbose_name='Registro Profesional'),
        ),
    ]
